### ISSUE TITLE
when no alive nodes, fail gracefully

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_elasticsearch#135]
currently a search fails with this error

`Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection() (line 51 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/libraries/elasticsearch-php/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php).`
presumably when ES connection is down.

would be better if it provided an error message but didnt break site.

**Comment by almasaeed2010** [comment]
Where does this happen? After search? In admin pages ...?

**Comment by bradfordcondon** [comment]
feature search on 8095from an organism, ie [chestnut](http://160.36.205.61:8095/bio_data/21)

**Comment by bradfordcondon** [comment]
nice.  

Are you sure its not better to return a warning that the site's ES is down?  The current way makes it seem like hte user just had a bad search.

**Comment by bradfordcondon** [comment]
re: wanting to open the page at a pane

https://github.com/tripal/tripal/issues/165
