### ISSUE TITLE
feature search on organism returns results from all species

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_elasticsearch#162]
I picked the example IPR term from F. pennsylvanica and get results from all species

http://160.36.205.61:8095/organism/Fraxinus/pennsylvanica?search_term=IPR020575&ds_pane=Feature%20Search

Feature search from the organism should auto-include a filter organism == current bundle organism.

**Comment by almasaeed2010** [comment]
So this query works on the gene search form itself http://160.36.205.61:8095/gene-search?organism=Fraxinus+pennsylvanica+%28Green+Ash%29&search_term=IPR020575&op=Search&form_build_id=form-_8JCvI3EjSL2XcFF2shZ2tjLVnwx9F4DLKibyDyfyRs&form_token=yJHI9Cst2jWXapKVCXdhaiutVIclNO5VR61LeTwz1CI&form_id=tripal_elasticsearch_gene_search_form

but not on the feature search field ... Makes it a bit easier to debug

**Comment by almasaeed2010** [comment]
Please test when you can. Close if all goes well.

Thanks!

**Comment by bradfordcondon** [comment]
looks good, way to go
