### ISSUE TITLE
collection problem: too many entities (need to udpate with API?)

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_elasticsearch#183]
* the tripal collections API has changed slightly as of this week.

* I created a collection with twenty two thousand entities.  However, the resulting collection has 40k entries?

![screen shot 2018-03-19 at 10 32 25 am](https://user-images.githubusercontent.com/7063154/37601698-1cd55c72-2b61-11e8-877e-33c3d3ebbdb7.png)

![screen shot 2018-03-19 at 10 33 14 am](https://user-images.githubusercontent.com/7063154/37601701-1e2a2710-2b61-11e8-9162-eadc275a2b30.png)

**Comment by bradfordcondon** [comment]
I think it doesnt involve the collecitons API.

dpming the entity array count that gets put into create collection:

![screen shot 2018-03-19 at 11 13 31 am](https://user-images.githubusercontent.com/7063154/37604111-988dd3f8-2b66-11e8-9324-b0748dc66613.png)

So it could be that the initial 798 is wrong?  

![screen shot 2018-03-19 at 11 12 17 am](https://user-images.githubusercontent.com/7063154/37604047-7c2a4cc8-2b66-11e8-8f0f-1440e341b8be.png)

**Comment by almasaeed2010** [comment]
I believe this has been fixed and tested
