### ISSUE TITLE
child/parent features need to be searchable

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_elasticsearch#190]
features are linked in chado via feature_relationship.  We are adding SSRs to genes via feature_relationship, and moving our entities from mrna to GENE for chestnut, where none of the sequences are even loaded into the gene.  see:
* https://github.com/statonlab/hardwoods_site/issues/226
* https://github.com/statonlab/hardwoods_site/issues/35

At the least, child/parent feature NAMES need to be indexed by ES.

**Comment by almasaeed2010** [comment]
So here is what I think we should do for this:
Let's simply look at the feature_relationship table and get a list of features that relate to the current feature and index nothing but their name in an array. This would be pretty simple if not for the fact that we use Eager Loading to speedup loading annotations. So adding this would potentially cause a memory leak. Let's add and test though.

**Comment by bradfordcondon** [comment]
update on this:

The official tripal way is to have the content you want associated pulled in explicitly by fields.  For example, the trnascript field is designed to display protein/mRNA sequences assocaited with a gene, on the gene page.

SO improving site wide search  should instead focus on creating these custom links as fields.

**Comment by almasaeed2010** [comment]
done
