### ISSUE TITLE
Gene URLs are not showing up

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_elasticsearch#194]
Feature search URLs are wrong and redirect to the home page.

**Comment by almasaeed2010** [comment]
Also, GO terms, IPR terms and blast descriptions are missing

**Comment by bradfordcondon** [comment]
make sure the acutal description exists, remember that our ontologies were kinda wonky with the definition field being blank for some

**Comment by almasaeed2010** [comment]
Fixed
