### ISSUE TITLE
Use ReadTheDocs

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_elasticsearch#215]
would be nice to have RTD here

**Comment by bradfordcondon** [comment]
I would only suggest doing the work of porting it over if we would benefit from the version control of RTD.  For example, if we release a new major version of this module but want the old documentation to still be easily accessible.

Otherwise, keeping the documentation in GitHub is totally fine.

**Comment by almasaeed2010** [comment]
I vote to keep it here since I doubt any big changes any time soon.
