### ISSUE TITLE
Clarify branches?

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal_elasticsearch#228]
Hi,
With @mboudet we're not sure which branches of this module are the *good* ones to be used with tripal 2 or 3.
Could you clarify it please?

**Comment by almasaeed2010** [comment]
Hello @abretaud 

The master branch is the one to use with both v2 and v3. This release detects and supports your version of Tripal 🙂 

We do plan on creating stable releases once we have enough people testing the current code.

Thanks!

**Comment by abretaud** [comment]
Ok, thanks for the quick answer!
