### ISSUE TITLE
Interacting with the module programmatically

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_elasticsearch#229]
Hello,

I'm trying to setup the module programmatically (as part of the tripal_rest_api module).
It worked up to a point, but currently, trying to programmatically index (with drupal_form_submit for example) is throwing up an error. Same thing when calling the underlying function.

Looking at the code, drupal_goto() is used several time in form_submit functions (and underlying functions), meaning that it will break when called programmatically.
(Example here)[https://github.com/tripal/tripal_elasticsearch/blob/9b1de440b4f78ee7712949c91a8d472fbfd5cd95/includes/tripal_elasticsearch.indices.form.inc#L920]

Is there any other way this could be done? I think using $form_state['redirect'] in the _submit function might work.

**Comment by bradfordcondon** [comment]
OK, I'm seeing 4 files using this function
https://github.com/tripal/tripal_elasticsearch/search?q=drupal_goto&unscoped_q=drupal_goto

In each case that uses a form I'll try using $form_state['redirect'] instead.

**Comment by almasaeed2010** [comment]
Merged. Thanks!
