### ISSUE TITLE
Unable to create new index

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal_elasticsearch#233]
I'm working to configure this module for the first time. I have the connection to my local elastic search set up (Local Elasticsearch Server Health shows status green).

When I go to create a new index (`admin/tripal/extension/tripal_elasticsearch/indices/create`), select an "Index Type" of "Website Nodes", and click "Create new index", I see the following error and the index is not created.

> {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: Could not convert [raw.index] to boolean"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: Could not convert [raw.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [raw.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [not_analyzed] as only [true] or [false] are allowed."}}},"status":400}

I also tried setting "Index Type" to "Tripal Entities" and after submitting tuning I see the same error.

**System information:**
Drupal: 7.63
Tripal: commit 3244f2dc184513d1c4576fb29b2d72e6f61d4413
PHP: 7.1.25
PostgreSQL: 9.4.10
Elasticsearch: 6.5.4

**Comment by almasaeed2010** [comment]
I haven't tested ES 6 yet. We've been using v5. I'll test v6 now and see if that's the issue.

Thanks!

**Comment by almasaeed2010** [comment]
I was able to create indices using ES 6. I think the documentation has an error though. Can you share the contents of your composer.json file in `sites/all/libraries/elasticsearch-php/composer.json`?

If the library version is 5, I'd attempt using `^6.0` instead by replacing the version in composer.json and running `composer update`.

Please let me know if that works so that I update the documentation.

Thanks!

**Comment by laceysanderson** [comment]
> I was able to create indices using ES 6. I think the documentation has an error though. Can you share the contents of your composer.json file in sites/all/libraries/elasticsearch-php/composer.json?

> If the library version is 5, I'd attempt using ^6.0 instead by replacing the version in composer.json and running composer update.

Unfortunately that didn't work 😕 I even tried clearing the cache just in case, as well as, trying both the "Website Nodes" and "Tripal entities".

Any other ideas about what to check? I'm at a bit of a loss since I'm unfamiliar with elasticsearch...

**Comment by almasaeed2010** [comment]
hmmmm which tripal_elasticsearch version are you using? Or is it from master?

(note that I tested the master branch)

**Comment by laceysanderson** [comment]
It's version 2.0 since the instructions said to check that version out. I'll try with master now

**Comment by almasaeed2010** [comment]
That's probably the issue. I should update the documentation to say to checkout the latest version rather than specifying a version

**Comment by laceysanderson** [comment]
Yay! That fixed it 😃 👍

**Comment by almasaeed2010** [comment]
Great! I think v2.1 was released to fix that issue but the notes doesn't seem to mention it ...

Thanks for letting us know!
