### ISSUE TITLE
Problem with tripal entity index 

### ISSUE THREAD

**Issue by songtaogui** [tripal/tripal_elasticsearch#237]
Hi, 

I am trying the elasticsearch using the test orange data from tripal site with drupal 7.x  and tripal v3.

When indexing tripal entity, there are neither progress bar in the `index progress tracker` page nor any warnigs, only says "All terms have been indexed", so I assumed that it was successfully indexed. But there are no search result provided.

Any suggestions? 

Thank you,

Best wishes,
Songtao Gui

**Comment by almasaeed2010** [comment]
Hello @songtaogui 

Can you visit the queue manager page at `admin/config/system/queue-ui` and let us know if there are any items that belong to `tripal_elasticsearch_*` queues?

Thanks!

**Comment by almasaeed2010** [comment]
Ok after some testing it looks like new indices are not being filled properly. On my local site, I get the following warnings: 

```
key() expects parameter 1 to be array, null given sbo__database_cross_reference.inc:125                                                   [warning]
```

```
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Missing $object argument to the chado_expand_var function from tripal_chado_field_storage_load (line: 413)
```

```
Creating default object from empty value BlastImporter.inc:834                                                                            [warning]
```

Each one repeated multiple times (on a per entity basis).

This could be the issue. It could also be that we use `Upsert` to insert or update if it already exists. instead of using `insert` directly. I'll try switching to `insert` to see if that fixes it.

**Comment by almasaeed2010** [comment]
Ok I figured out what my issue was. This module does not index items that are not accessible to anonymous users. Therefore, you have to first make any content that you want indexed available to anonymous users through the `people > permissions` page.

To fix:
1. Visit `/admin/people/permissions`
1. Under the section marked **Tripal**, allow anonymous users to view content. For example, find and mark `Organism: View Content` as available to anonymous users.
1. Rerun the indexing process by visiting the indices page and clicking update. You could also simply delete the index and recreate it if the update function doesn't work.

Please let us know if this works for you.

Thanks!

**Comment by songtaogui** [comment]
@almasaeed2010 

Yes, it works. Thank you for your kind help!

👍 👍

**Comment by almasaeed2010** [comment]
Added info to docs b6f35a0015bdf5fb5980eeb15a43bdb00fd2d889
