### ISSUE TITLE
Local gene search does not work properly for 'Any organism'

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_elasticsearch#253]
Hello,

When using the local gene search, I properly get results when I select my organism : 

![image](https://user-images.githubusercontent.com/17642511/53800193-72e97180-3f3c-11e9-8ba5-80023f798aed.png)

However, if I select 'Any organism', no results are found.

![image](https://user-images.githubusercontent.com/17642511/53800246-93b1c700-3f3c-11e9-8f70-cf16c42f4961.png)

Shouldn't 'Any organism' results at least include results from my organism?

**Comment by almasaeed2010** [comment]
Hi @mboudet thanks for reporting. 

I can replicate this issue on our live site.

**Comment by almasaeed2010** [comment]
This issue has been fixed on master.

If it doesn't work for you @mboudet, please let us know.

Thanks!

**Comment by mboudet** [comment]
It works fine when looking for a term.
However, without a research term, 'Any organism' shows nothing (not even a no result message)
Whereas selecting an organism does give results.

![image](https://user-images.githubusercontent.com/17642511/53811659-2d3ba180-3f5a-11e9-85fc-818bd0989591.png)
![image](https://user-images.githubusercontent.com/17642511/53811706-43e1f880-3f5a-11e9-8d1d-1ef23a757126.png)

**Comment by almasaeed2010** [comment]
We applied a fix to make sure results get displayed when an empty form is submitted. The new behavior will simply list all the contents of the index for you to navigate.
