### ISSUE TITLE
cron instructions

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_elasticsearch#261]
I seem to remember we had cron setup instructions, however, i didn't find them reading through the guide.

**Comment by almasaeed2010** [comment]
It's still there. But we are missing the links that go to it ... https://github.com/tripal/tripal_elasticsearch/blob/master/docs/queues.md

**Comment by almasaeed2010** [comment]
Fixed on master. Let me know if we need to add more instructions.

Thanks!
