### ISSUE TITLE
drupal search api (tripal)

### ISSUE THREAD

**Issue by Yosra3** [tripal/tripal_elasticsearch#263]
Hello
i'm using the module drupal search api with tripal.
I can't define a search index, i had this page

![image](https://user-images.githubusercontent.com/47979265/57832556-347ff680-77b8-11e9-9eeb-1e23b35d998c.png)

on the log message i got this:
![image](https://user-images.githubusercontent.com/47979265/57832587-4b264d80-77b8-11e9-9420-2ce19a6350b5.png)

Who can help me to resolve this error !! Thank you

**Comment by almasaeed2010** [comment]
Hello @Yosra3 

This module does not integrate with the Drupal Search API. We haven't used that API before so I am not sure we help. If you'd like help with installing and managing Tripal Elasticsearch, please let us know!

Sorry we couldn't help!
