### ISSUE TITLE
user reports that entities arent being indexed for custom index

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_elasticsearch#264]
from https://github.com/tripal/tripal/issues/979 reported by @theBowja

Hi.

>I have an custom index on two bundles: mRNA and Transcript (I added this one). When I publish tripal content like mrna or transcript, the index does not show that there are any new things to index. It'll say something like 0/0 indexed. I have to disable then enable the index in order for those published content to show up for indexing.
>Within the edit tab for adding an index there is an option "Index items immediately". I would like to either get this working or figure out how to make indexing as a tripal job instead. Currently I have to click "Index now" in the browser and leave it open which is very tiring if there is a lot of records to index.
>Does anyone have any insight to my problem or where I should start? I'm using tripal 7.x-3.1.

**Comment by almasaeed2010** [comment]
Hi! I don't believe this is an elasticsearch issue. Could it be the [Drupal Search Module](https://www.drupal.org/docs/7/core/modules/search/overview)?

**Comment by bradfordcondon** [comment]
my bad sorry

**Comment by almasaeed2010** [comment]
No problem!
