### ISSUE TITLE
no handler for type text

### ISSUE THREAD

**Issue by theBowja** [tripal/tripal_elasticsearch#265]
I created an mview and I have the field: 
`    'description' => array (
      'type' => 'text',
      'not null' => true,
    ),`
I went to create an tripal elasticsearch index on that
when I selected "text" for "Field name: description", I get:
`mapper_parsing_exception: No handler for type [text] declared on field [description]`

**Comment by theBowja** [comment]
err what's the version requirement for elasticsearch?

**Comment by almasaeed2010** [comment]
Hello @theBowja 

Sorry for the delay on this. We are using ElasticSearch 6 and haven't encountered issues. Is that the version you use? I believe they started using the `text` type since version 5.
