### ISSUE TITLE
how to index custom fields for content types/bundles

### ISSUE THREAD

**Issue by mpoelchau** [tripal/tripal_elasticsearch#275]
This is not really an issue but a question about custom indices. We'd like to index additional fields for bundles beyond the default provided by the entities indexer. For example, there is a lot of information in the featureprop table associated with our genes and mRNAs that users will likely search for that need to be included in the index. We've looked at the interface to build custom indices, but when we select the chado_bio_data_x table associated with the bundle type (e.g. gene), only the fields from that table are shown as options for indexing (mapping_id, entity_id, record_id, nid - whereas we'd want to index particular cvterms, not to mention many fields from the feature table).

How would you recommend indexing additional fields for different chado bundle types? Will this require a code change? 

Thanks for your help with this!

**Comment by almasaeed2010** [comment]
Hello @mpoelchau 

The first thing that comes to mind is to create a Tripal Field. By creating a field and attaching it to the entities that should be linked to in the results, you'll be able to tell the entities indexer to consider it and at the same time tell Tripal to not display it. 

Please let me know if this helps

**Comment by almasaeed2010** [comment]
To clarify, Tripal Elasticsearch allows you to choose which fields to index by visiting the `Tuning Form` at `/admin/tripal/extension/tripal_elasticsearch/tuning` or from the admin menu -> Tripal -> Extensions -> Tripal Elasticsearch -> Tuning.

**Comment by mpoelchau** [comment]
The fields are already associated with this content type, and they display on the page as currently configured. Here's a screenshot of the fields that are displayed for the gene bundle:

<img width="695" alt="Screen Shot 2021-01-08 at 11 31 52 AM" src="https://user-images.githubusercontent.com/5487172/104051328-34aae200-51a5-11eb-8111-f008103c10ae.png">

And here are some of those properties on a gene page: 

<img width="878" alt="Screen Shot 2021-01-08 at 11 33 42 AM" src="https://user-images.githubusercontent.com/5487172/104051452-61f79000-51a5-11eb-9d47-0741f9766f54.png">

**Comment by almasaeed2010** [comment]
Can you try visiting the tuning form and make sure the field is set to High Priority?

**Comment by mpoelchau** [comment]
Thanks @almasaeed2010 we totally missed the tuning page. I believe that should do what we want! We still need to test but I'll close the issue for now.
